// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOiY7YCQNpzrNR__pVL1tzqTRAbjdjHkg',
    appId: '1:1038107293843:web:06222b6478b76812d13566',
    messagingSenderId: '1038107293843',
    projectId: 'pearlline-dental',
    authDomain: 'pearlline-dental.firebaseapp.com',
    storageBucket: 'pearlline-dental.firebasestorage.app',
    measurementId: 'G-YEDSYKX3C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx52i9OFdxSQNqxMDZgkJoJJr1rjhoUho',
    appId: '1:1038107293843:android:a6833f2e8cfc2a33d13566',
    messagingSenderId: '1038107293843',
    projectId: 'pearlline-dental',
    storageBucket: 'pearlline-dental.firebasestorage.app',
  );
}
